version: '3.7'

services:

  maria_db:
    container_name: mariadbsrv
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 'example'
      MARIADB_PASSWORD: 'mycoolsecret'
      MARIADB_USER: 'exampleuser'
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'no'
      MARIADB_DATABASE: 'wordpress'
    ports: 
      - 3307:3307
    volumes:
      - maria-db-data:/var/lib/mariadb

  adminer:
    container_name: adminersrv
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DESIGN: kahi
      ADMINER_DEFAULT_SERVER: maria_db     
    ports:
      - 9080:8080
    depends_on:
      - maria_db 

  phpmyadmin:
    container_name: phasrv
    image: phpmyadmin
    restart: always
    ports:
      - 9081:80
    environment:
      PMA_ARBITRARY: '1'
      PMA_HOST: mariadbsrv
      PMA_USER: root
      PMA_PASSWORD: secret
    depends_on:
      - maria_db    

volumes:
 maria-db-data:
   labels:
    - "net.tr.description=MariaDB"
    - "net.tr.department=Dromadero"