version: '3.7'

services:

  mysql_db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 'example'
      MARIADB_PASSWORD: 'mycoolsecret'
      MARIADB_USER: 'exampleuser'
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'no'
    ports: 
      - 3307:3307
    volumes:
      - maria-db-data:/var/lib/mariadb

  adminer:
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DESIGN: kahi
      ADMINER_DEFAULT_SERVER: mysql_db
    depends_on:
      - mysql_db      
    ports:
      - 9080:8080


volumes:
 maria-db-data:
   labels:
    - "net.tr.description=MariaDB"
    - "net.tr.department=Dromadero"